MODULE GSTATS_WRAPPER_MOD
  CONTAINS
  SUBROUTINE GSTATS_WRAPPER(KNUM,KSWITCH,LABEL)
  USE EC_PARKIND  ,ONLY : JPRD, JPIM ,JPIB
  USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK, JPHOOK

  USE YOMGSTATS  
  USE MPL_MODULE
  USE MPL_STATS_MOD
  USE OML_MOD
  USE hip_profiling   ,ONLY : roctxRangePushA,&
                              roctxRangePop,&
                              roctxMarkA
  USE iso_c_binding   ,ONLY : C_CHAR, c_null_char
  IMPLICIT NONE
  INTEGER :: ret
  INTEGER(KIND=JPIM),INTENT(IN) :: KNUM
  INTEGER(KIND=JPIM),INTENT(IN) :: KSWITCH
  CHARACTER(C_CHAR) :: LABEL(*)

  CALL GSTATS(KNUM,KSWITCH)
  IF (KSWITCH > 0) THEN
     CALL roctxRangePop()
     CALL roctxMarkA(CCDESC(KNUM))
  ELSE
     ret = roctxRangePushA(CCDESC(KNUM))
  ENDIF


  END SUBROUTINE GSTATS_WRAPPER
END MODULE GSTATS_WRAPPER_MOD
